version: "3.9"
services:
  app:
    build:
      context: .
      target: production
    command: npm run start
    env_file: .env
    expose:
      - ${SVR_PORT}
    ports:
      - ${PROD_PORT}:${SVR_PORT}